# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 11:13
from __future__ import unicode_literals

import correctiv_ttip_barometer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_ttip_barometer', '0004_chapter_long_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=correctiv_ttip_barometer.models.document_path),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Just started.'), (15, 'No agreement in sight.'), (30, "It's complicated."), (60, "There's a first contract draft."), (75, 'Agreement in sight.'), (100, 'The contract is concluded.')], default=15),
        ),
    ]
