# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_ttip_barometer', '0005_auto_20160512_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('long_title', models.CharField(max_length=512)),
                ('teaser', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='correctiv_ttip_barometer.Chapter')),
            ],
            options={
                'managed': True,
                'db_table': 'correctiv_ttip_barometer_chapter_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'chapter Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chaptertranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
