# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 08:32
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import ObjectDoesNotExist
from django.conf import settings


def forwards_func(apps, schema_editor):
    Chapter = apps.get_model('correctiv_ttip_barometer', 'Chapter')
    ChapterTranslation = apps.get_model('correctiv_ttip_barometer', 'ChapterTranslation')

    for object in Chapter.objects.all():
        ChapterTranslation.objects.create(
            master_id=object.pk,
            language_code=settings.LANGUAGE_CODE,
            title=object.title,
            slug=object.slug,
            long_title=object.long_title,
            teaser=object.teaser,
            body=object.body,
        )


def backwards_func(apps, schema_editor):
    Chapter = apps.get_model('correctiv_ttip_barometer', 'Chapter')
    ChapterTranslation = apps.get_model('correctiv_ttip_barometer', 'ChapterTranslation')

    for object in Chapter.objects.all():
        translation = _get_translation(object, ChapterTranslation)
        object.title = translation.title
        object.slug = translation.slug
        object.long_title = translation.long_title
        object.teaser = translation.teaser
        object.body = translation.body
        object.save()   # Note this only calls Model.save() in South.


def _get_translation(object, MyModelTranslation):
    translations = MyModelTranslation.objects.filter(master_id=object.pk)
    try:
        # Try default translation
        return translations.get(language_code=settings.LANGUAGE_CODE)
    except ObjectDoesNotExist:
        try:
            # Try default language
            return translations.get(language_code=settings.PARLER_DEFAULT_LANGUAGE_CODE)
        except ObjectDoesNotExist:
            # Maybe the object was translated only in a specific language?
            # Hope there is a single translation
            return translations.get()


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_ttip_barometer', '0006_auto_20160525_1032'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
