# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_ttip_barometer', '0007_auto_20160525_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='body',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='long_title',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='teaser',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='title',
        ),
    ]
