# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 08:37
from __future__ import unicode_literals

import correctiv_ttip_barometer.models
from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_ttip_barometer', '0008_auto_20160525_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=correctiv_ttip_barometer.models.document_path)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correctiv_ttip_barometer.Chapter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
