# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 08:38
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Chapter = apps.get_model("correctiv_ttip_barometer", "Chapter")
    ChapterDocument = apps.get_model("correctiv_ttip_barometer", "ChapterDocument")

    for chapter in Chapter.objects.all():
        if chapter.document:
            doc = ChapterDocument(
                chapter=chapter,
            )
            doc.document.name = chapter.document.name
            doc.save()


def reverse_func(apps, schema_editor):
    ChapterDocument = apps.get_model("correctiv_ttip_barometer", "ChapterDocument")
    for doc in ChapterDocument.objects.all():
        doc.chapter.document.name = doc.document.name
        doc.chapter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_ttip_barometer', '0009_auto_20160608_1037'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
