# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_ttip_barometer', '0010_auto_20160608_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='document',
        ),
    ]
