# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_ttip_barometer', '0011_remove_chapter_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterDocumentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='correctiv_ttip_barometer.ChapterDocument')),
            ],
            options={
                'managed': True,
                'db_table': 'correctiv_ttip_barometer_chapterdocument_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'chapter document Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapterdocumenttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
