# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_ttip_barometer', '0012_auto_20160608_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterdocument',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterField(
            model_name='chaptertranslation',
            name='long_title',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
